"""Generate ``docs/reference/configuration.md`` from ``sgblur_video.config.Settings``.

The configuration reference is never edited by hand: field descriptions,
defaults, groups and privacy notes live next to the code. Run without
arguments to rewrite the file, or with ``--check`` to fail (exit code 1) when
it is out of date (used by a unit test and a pre-commit hook).

Usage:
    uv run python scripts/gen_config_reference.py [--check]
"""

import argparse
import json
import sys
import types
from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Literal, Union, get_args, get_origin

from pydantic import SecretStr
from pydantic.fields import FieldInfo

from sgblur_video.config import Settings

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "reference" / "configuration.md"

HEADER = """\
# Configuration reference

<!-- Generated by scripts/gen_config_reference.py from src/sgblur_video/config.py. Do not edit. -->

Every setting is read from the environment variable of the same name (case
insensitive, no prefix) or from a `.env` file in the working directory.
Lists accept comma-separated values; `CLASS_POLICY` takes a JSON object.

The **Privacy** column says what loosening a setting does. Settings with a
privacy note must not be changed without running the privacy benchmark
(see [testing strategy](../design/testing-strategy.md)).
"""


_SIMPLE_NAMES = {
    "str": "string",
    "int": "integer",
    "float": "number",
    "bool": "boolean",
    "Path": "path",
    "HttpUrl": "URL",
}


def _type_name(annotation: Any) -> str:  # noqa: ANN401 - annotations are arbitrary objects
    """Render a field annotation as a short, human-readable type."""
    origin, args = get_origin(annotation), get_args(annotation)
    if origin is Annotated:
        return _type_name(args[0])
    if origin is Literal:
        return " \\| ".join(f"`{arg}`" if isinstance(arg, str) else f"`{str(arg).lower()}`" for arg in args)
    if origin in (Union, types.UnionType):
        return " \\| ".join(_type_name(arg) for arg in args if arg is not type(None))
    if origin in (list, tuple):
        return f"list of {_type_name(args[0])}"
    if origin is dict:
        return "JSON object"
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return " \\| ".join(f"`{member.value}`" for member in annotation)
    if annotation is SecretStr:
        return "secret"
    name = getattr(annotation, "__name__", str(annotation))
    return _SIMPLE_NAMES.get(name, name)


def _default(field: FieldInfo) -> str:
    """Render a field default for the documentation."""
    extra = field.json_schema_extra if isinstance(field.json_schema_extra, dict) else {}
    if "doc_default" in extra:
        return f"`{extra['doc_default']}`"
    value = field.get_default(call_default_factory=True)
    if value is None:
        return "empty"
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, dict):
        return "`" + json.dumps({k: getattr(v, "value", v) for k, v in value.items()}) + "`"
    if isinstance(value, list):
        return "`" + ",".join(map(str, value)) + "`" if value else "empty"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def render() -> str:
    """Build the Markdown reference.

    Returns:
        The full content of ``docs/reference/configuration.md``.
    """
    groups: dict[str, list[str]] = {}
    for name, field in Settings.model_fields.items():
        extra = field.json_schema_extra if isinstance(field.json_schema_extra, dict) else {}
        group = str(extra.get("group", "Other"))
        privacy = str(extra.get("privacy", "")) or "—"
        description = (field.description or "").replace("|", "\\|")
        cells = [f"`{name.upper()}`", _type_name(field.annotation), _default(field), description, privacy]
        row = "| " + " | ".join(cells) + " |"
        groups.setdefault(group, []).append(row)
    lines = [HEADER]
    for group, rows in groups.items():
        lines += [
            f"\n## {group}\n",
            "| Variable | Type | Default | Description | Privacy |",
            "|---|---|---|---|---|",
            *rows,
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write or check the reference file.

    Returns:
        Process exit code: 0 on success, 1 if ``--check`` finds a stale file.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT} is out of date: run scripts/gen_config_reference.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
